# live_config.py -- the per-symbol config the live quoter reads at startup and
# re-reads every REFRESH_SECONDS, so a name can be switched from lean to lean-off,
# or pulled entirely, without restarting the book.
#
# TWO FILES, NOT ONE. This is the one design change I am pushing back on.
#   ASSIGNMENT  config_assignment_YYYYMMDD_HHMM.csv -- machine-generated by
#               build_config_assignment.py, 113 rows, NEVER hand-edited.
#               Lives in RESULTS_ROOT with the other run outputs.
#   OVERRIDES   live_overrides.csv -- hand-edited, sparse (usually 0-3 rows),
#               wins over the assignment for the symbols it names.
#               Lives in existing_mm_live/, beside this file.
# Why: during an earnings halt you are editing a file under time pressure. A
# 3-row file you can read at a glance is a different risk from a 113-row
# machine-generated file where a stray keystroke on the wrong line silently
# changes a name you never looked at. It also means the next refit can drop a new
# assignment in without clobbering a manual intervention that is still live.
#
# FAILURE POLICY -- deliberately asymmetric:
#   AT STARTUP   a bad file is fatal. There is no last-good config to fall back
#                to, and starting on engine defaults would quote 113 names on a
#                config nobody chose. Refuse to start.
#   ON RELOAD    a bad file is IGNORED and the last good config stays live, with
#                a loud log line. Dropping the whole book because someone saved a
#                CSV mid-edit is worse than running the previous config for
#                another three minutes.
#
# TORN READS. The file may be read while an editor is writing it. This module
# reads the bytes in one shot and parses from memory, so a half-written file
# fails validation and is rejected rather than half-applied. Write new
# assignments with a temp file plus os.replace() so the swap is atomic.
#
# ABSENCE IS NOT AN INSTRUCTION. If a symbol stops appearing in the assignment,
# it keeps running on its last setting. Stopping a name requires writing DROP
# against it explicitly. A missing row has too many innocent causes to be read as
# "stop trading this". The cost of that rule is a name that a refit legitimately
# dropped would keep quoting unnoticed, so every such symbol is re-warned on
# EVERY reload (not once), appears in summary(), and is listed by the preflight.
#
# WHAT THIS MODULE DOES NOT DECIDE. What "DROP" means for a name that already
# holds inventory. See DROP_SEMANTICS below -- that choice is yours and the
# module refuses to guess.

from __future__ import annotations
# stdlib only on the live path: no pandas, so a CSV parse cannot pull in a heavy
# import or a version-dependent dtype coercion mid-session
import csv, hashlib, io, logging, os, threading, time
from pathlib import Path

# ---------------------------------------------------------------------------
# PATHS -- from config_pk, and on the live path a missing config_pk is FATAL.
# There is deliberately no fallback literal here. A backtest that silently reads
# the wrong store wastes an afternoon; a live book that does is a real loss.
# ---------------------------------------------------------------------------
try:
    # the project's central path module -- the only place a path is written down
    from config_pk import RESULTS_ROOT
except Exception as _e:
    # fail at import, naming the fix, rather than anywhere later
    raise ImportError(
        "live_config: could not import RESULTS_ROOT from config_pk. Run from the "
        "existing_mm_live/ directory, or put it on sys.path. Original: %r" % _e)

# the machine-generated assignment currently shipped -- lives with the run
# outputs, because build_config_assignment.py writes it there
ASSIGNMENT_PATH = RESULTS_ROOT / "config_assignment_20260915_0043.csv"
# The sparse hand-edited intervention file, which SZ keeps in existing_mm_live
# next to the code rather than among the run outputs -- it is opened under time
# pressure and must be one keystroke away, not buried in a results directory.
# Resolved RELATIVE TO THIS FILE rather than written out as a literal: it is not
# a hardcoded path, so moving the checkout cannot make it stale, and it needs no
# new entry in config_pk.py. May legitimately not exist.
OVERRIDES_PATH = Path(__file__).resolve().parent / "live_overrides.csv"
# how often the live loop should call refresh()
REFRESH_SECONDS = 180

# ---------------------------------------------------------------------------
# THE LABEL TABLE -- must stay identical to build_config_assignment.py's PARAMS.
# ---------------------------------------------------------------------------
# each label maps to (queue_skew_ticks, queue_skew_thresh, quote?)
# NOTE on the threshold for "lean off": build_config_assignment.py records NaN
# there because the threshold is meaningless when the lean is off. Do NOT pass a
# NaN into the engine -- every comparison against NaN is False, so it would
# happen to work today and break silently the first time someone writes
# `if thresh <= x` instead of `>`. Pass the engine's own default (0.15), which is
# inert while ticks == 0.
LABELS = {
    # the lean, firing once the book is 0.15 past balanced
    "QT_2t@15": (2.0, 0.15, True),
    # the same lean, firing less often
    "QT_2t@20": (2.0, 0.20, True),
    # lean off: quote symmetrically
    "OBI":      (0.0, 0.15, True),
    # not quoted at all
    "DROP":     (0.0, 0.15, False),
}

# accepted spellings for the same thing, so a hand-edited override file can say
# something a human would actually type at 14:00 under pressure
ALIASES = {
    "LEAN": "QT_2t@15", "LEAN15": "QT_2t@15", "QT_2T@15": "QT_2t@15",
    "LEAN20": "QT_2t@20", "QT_2T@20": "QT_2t@20",
    "OFF": "OBI", "LEANOFF": "OBI", "LEAN_OFF": "OBI",
    "STOP": "DROP", "PULL": "DROP", "HALT": "DROP",
}

# ---------------------------------------------------------------------------
# DROP SEMANTICS -- you must choose. There is no safe default.
# ---------------------------------------------------------------------------
#   "no_add"  stop quoting the side that would ADD to the position; keep quoting
#             the reducing side so inventory works off passively. This is what
#             "pull the name, I don't want new risk into earnings" usually means.
#   "flat"    stop quoting entirely and hold whatever is on the book. Only right
#             if something else is responsible for the position.
#   "cross"   cross out immediately at market. Guarantees flat, pays the spread
#             (5.3-79 bps depending on the name -- see the hedge cost work).
# CHOSEN 2026-09-15: "no_add". It needs no engine change -- micro_mm's soft_inv
# band already implements it, and params_for() emits soft_inv=0 to switch it on.
# Note what "no_add" does NOT do: it stops you getting deeper, it does not get
# you out. If the reason for pulling a name is that you want to be FLAT before an
# announcement rather than merely not-longer, no_add will not achieve that and
# "cross" is the only setting that will.
DROP_SEMANTICS = "no_add"

# module logger; the live app should attach its own handler
log = logging.getLogger("live_config")


class ConfigError(Exception):
    """Raised when a config file is unusable. Fatal at startup, caught on reload."""


def _read_bytes(path: Path) -> bytes:
    # single read() so an editor writing the file cannot give us two halves from
    # two different versions -- we either get a coherent file or a broken one
    with open(path, "rb") as fh:
        return fh.read()


def _parse(raw: bytes, path: Path, need_symbol_col=True) -> dict:
    """Parse assignment or override CSV bytes into {symbol: label}. Raises ConfigError."""
    # decode strictly: a mojibake file is a corrupt file, not something to coerce
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as e:
        raise ConfigError(f"{path.name}: not valid UTF-8 ({e})")
    # parse from memory, never from the live file handle
    rdr = csv.DictReader(io.StringIO(text))
    # a file with no header at all is corrupt, not empty
    if rdr.fieldnames is None:
        raise ConfigError(f"{path.name}: no header row")
    # the two columns this module needs
    cols = set(rdr.fieldnames)
    # the symbol column is mandatory in both files
    if need_symbol_col and "symbol" not in cols:
        raise ConfigError(f"{path.name}: no 'symbol' column; has {sorted(cols)}")
    # the assignment writes 'assigned_config'; an override file may use either
    label_col = "assigned_config" if "assigned_config" in cols else \
                ("config" if "config" in cols else None)
    # without a label column there is nothing to apply
    if label_col is None:
        raise ConfigError(
            f"{path.name}: no 'assigned_config' or 'config' column; has {sorted(cols)}")
    # accumulate here so a bad row aborts the whole file rather than half-applying
    out = {}
    # walk the rows, counting from 2 because row 1 is the header
    for i, row in enumerate(rdr, start=2):
        # the symbol, normalised
        sym = (row.get("symbol") or "").strip().upper()
        # a blank line at the end of a hand-edited file is not an error
        if not sym:
            continue
        # COMMENT ROWS. A line whose symbol cell starts with '#' is a note, not a
        # symbol. This exists so the operator can record WHY a name was pulled at
        # 14:00 in the same file as the instruction -- otherwise that reason
        # lives only in someone's head and post-trade cannot reconstruct the day.
        if sym.startswith("#"):
            continue
        # the label as written
        lab = (row.get(label_col) or "").strip()
        # an empty label is a half-finished edit -- refuse the file
        if not lab:
            raise ConfigError(f"{path.name} line {i}: symbol {sym} has an empty {label_col}")
        # resolve an alias if one was used
        lab = ALIASES.get(lab.upper(), lab)
        # HARD FAILURE on an unknown label. This is the whole point: a typo must
        # never fall through to a default, because a name quietly running the
        # wrong config is invisible until the P&L attribution months later.
        if lab not in LABELS:
            raise ConfigError(
                f"{path.name} line {i}: symbol {sym} has unknown setting {lab!r}; "
                f"valid: {sorted(LABELS)} (aliases: {sorted(ALIASES)})")
        # a symbol listed twice means two people edited, or one edited twice
        if sym in out:
            raise ConfigError(f"{path.name} line {i}: symbol {sym} appears more than once")
        # accept the row
        out[sym] = lab
    # an assignment with no rows is corrupt; an override file with none is normal
    if need_symbol_col and not out and path == ASSIGNMENT_PATH:
        raise ConfigError(f"{path.name}: parsed zero rows")
    return out


class LiveConfig:
    """Hot-reloadable per-symbol config. One instance; call refresh() on a timer."""

    def __init__(self, assignment_path=ASSIGNMENT_PATH, overrides_path=OVERRIDES_PATH):
        # where the machine-generated baseline lives
        self.assignment_path = Path(assignment_path)
        # where the sparse hand-edited interventions live
        self.overrides_path = Path(overrides_path)
        # the last config that parsed cleanly: {symbol: label}
        self._live: dict[str, str] = {}
        # content hashes of the last accepted files, so an unchanged file is a no-op
        self._hashes: dict[str, str] = {}
        # which symbols are currently coming from the override file
        self._overridden: set[str] = set()
        # symbols still live but no longer present in the assignment file --
        # carried forward at their last setting, and re-warned on every reload
        self._orphans: set[str] = set()
        # guards _live against a reload landing mid-read from the quoting thread
        self._lock = threading.RLock()
        # when the last successful load finished
        self.last_good_ts: float | None = None
        # how many consecutive reloads have failed (for alerting)
        self.consecutive_failures = 0
        # STARTUP: load once, and let any error propagate. There is nothing in
        # memory to fall back to, so a bad file here must stop the launch rather
        # than start 113 names on a config nobody chose this morning.
        self._load()

    # -- loading ------------------------------------------------------------

    def _load(self) -> dict[str, tuple[str, str]]:
        """Read both files and swap them in. Returns {symbol: (old, new)} changes."""
        # the baseline must exist
        if not self.assignment_path.exists():
            raise ConfigError(f"assignment not found: {self.assignment_path}")
        # read and hash the baseline
        raw_a = _read_bytes(self.assignment_path)
        # the override file is optional by design
        raw_o = _read_bytes(self.overrides_path) if self.overrides_path.exists() else b""
        # content hashes: cheaper and more honest than mtime, which an editor or
        # a copy can bump without changing anything
        h = {"assignment": hashlib.sha1(raw_a).hexdigest(),
             "overrides": hashlib.sha1(raw_o).hexdigest()}
        # nothing changed since the last accepted load -> no work, no log spam
        if h == self._hashes and self._live:
            return {}
        # parse the baseline (raises on any problem)
        merged = _parse(raw_a, self.assignment_path)
        # parse the overrides, if there are any
        overridden = set()
        if raw_o.strip():
            ov = _parse(raw_o, self.overrides_path)
            # an override naming a symbol not in the assignment is a typo, not a
            # new name -- the universe is decided by the refit, not at 14:00
            unknown = sorted(set(ov) - set(merged))
            if unknown:
                raise ConfigError(
                    f"{self.overrides_path.name}: symbols not in the assignment: {unknown}")
            # overrides win
            merged.update(ov)
            # remember which ones, so the log can say where a setting came from
            overridden = set(ov)
        # ABSENCE NEVER CHANGES BEHAVIOUR. A symbol that has dropped out of the
        # assignment keeps whatever setting it is already running. Stopping a
        # name requires writing DROP against it -- an explicit instruction, not
        # the absence of one. Too many innocent things produce a missing row (a
        # filtered export, a copy-paste that lost lines, an editor truncating a
        # save) and none of them should silently change what is quoted.
        orphans = set(self._live) - set(merged)
        # carry each orphan forward at the setting it is already running
        for s in orphans:
            merged[s] = self._live[s]
        # diff against what is live right now -- orphans never appear here,
        # because by construction their setting did not change
        changes = {s: (self._live.get(s, "-"), lab)
                   for s, lab in merged.items() if self._live.get(s) != lab}
        # swap atomically for the quoting thread
        with self._lock:
            self._live = merged
            self._overridden = overridden
            self._orphans = orphans
            self._hashes = h
            self.last_good_ts = time.time()
        return changes

    def refresh(self) -> dict[str, tuple[str, str]]:
        """Call every REFRESH_SECONDS. Never raises. Returns the changes applied."""
        try:
            # try to pick up the new files
            changes = self._load()
        except Exception as e:
            # RELOAD POLICY: keep the last good config, shout, carry on
            self.consecutive_failures += 1
            log.error("live_config reload REJECTED (%d in a row), keeping the "
                      "config loaded at %s: %s", self.consecutive_failures,
                      time.strftime("%H:%M:%S", time.localtime(self.last_good_ts or 0)), e)
            return {}
        # a clean load resets the alert counter
        self.consecutive_failures = 0
        # AUDIT TRAIL: every change, named, so post-trade can explain the day
        for sym, (old, new) in sorted(changes.items()):
            log.warning("live_config CHANGE %-8s %-9s -> %-9s%s",
                        sym, old, new, "  (override)" if sym in self._overridden else "")
        # ORPHAN WARNING, re-emitted EVERY reload rather than once. A name that
        # has fallen out of the assignment keeps trading on its old setting, by
        # design -- but that is exactly the state nobody notices, so it is said
        # again every three minutes until the file is fixed or DROP is written.
        with self._lock:
            orphans = sorted(self._orphans)
        if orphans:
            log.warning("live_config ORPHANS still quoting on their last setting, "
                        "absent from %s: %s  -- write DROP against them to stop "
                        "them, or re-add them to the assignment",
                        self.assignment_path.name, ", ".join(orphans))
        return changes

    # -- what the quoter asks -----------------------------------------------

    def params_for(self, symbol: str) -> dict | None:
        """Engine kwargs for one symbol, or None if the symbol is not in the book.

        Returns e.g. {"queue_skew_ticks": 2.0, "queue_skew_thresh": 0.15,
                      "quote": True, "label": "QT_2t@15", "drop_semantics": None}
        Feed the two queue_skew_* values into mm_harness's `overrides` dict.
        """
        # read under the lock so a reload cannot swap the dict mid-lookup
        with self._lock:
            lab = self._live.get(symbol.strip().upper())
        # a symbol the refit never assigned is not tradeable -- say so explicitly
        # rather than returning a default the caller might quote on
        if lab is None:
            return None
        # the numbers this label stands for
        ticks, thresh, quote = LABELS[lab]
        # the kwargs the harness will splice into its `overrides` dict
        out = {
            # the lean, in ticks; 0.0 means the lean is off
            "queue_skew_ticks": ticks,
            # how lopsided the book must be before the lean fires
            "queue_skew_thresh": thresh,
            # False means this name is pulled -- see drop_semantics
            "quote": quote,
            # the machine label, for logging and P&L attribution
            "label": lab,
            # only meaningful when quote is False; the caller acts on it
            "drop_semantics": None if quote else DROP_SEMANTICS,
        }
        # DROP under "no_add" needs NO engine change -- micro_mm's soft_inv band
        # already is this mechanism: once |pos| > soft_inv, the side that would
        # ADD to the position stops being quoted, so fills can only reduce.
        # soft_inv=0 therefore means "never add, only work out".
        if not quote and DROP_SEMANTICS == "no_add":
            # once holding anything at all, quote the reducing side only
            out["soft_inv"] = 0
            # CAVEAT the caller must honour: soft_inv=0 does NOT stop a FLAT name
            # from quoting both sides, because the band only binds at |pos| > 0.
            # So a dropped name that is already flat must be skipped entirely --
            # do not construct a strategy for it. The two cases are:
            #   position == 0  -> do not quote this symbol at all
            #   position != 0  -> quote with these kwargs (soft_inv=0), which
            #                     works the inventory off passively and never
            #                     adds to it
            out["skip_if_flat"] = True
        return out

    def symbols(self, quoting_only=True) -> list[str]:
        """The symbols in the book. quoting_only=True excludes the DROP names."""
        with self._lock:
            items = list(self._live.items())
        return sorted(s for s, lab in items if (LABELS[lab][2] or not quoting_only))

    def summary(self) -> str:
        """One line for the startup log and for any health endpoint."""
        with self._lock:
            live = dict(self._live)
            ov = len(self._overridden)
            orph = len(self._orphans)
        # count the names on each setting
        counts = {lab: sum(1 for v in live.values() if v == lab) for lab in LABELS}
        return (f"{len(live)} names | "
                + " ".join(f"{lab}={counts[lab]}" for lab in LABELS)
                + f" | {ov} override(s)"
                # only mention orphans when there are some, so the normal line
                # stays clean and the abnormal one stands out
                + (f" | {orph} ORPHAN(S)" if orph else "")
                + " | loaded "
                + time.strftime("%H:%M:%S", time.localtime(self.last_good_ts or 0)))

    def orphans(self) -> list[str]:
        """Symbols still quoting but no longer in the assignment file."""
        with self._lock:
            return sorted(self._orphans)


# ---------------------------------------------------------------------------
# Run this file directly to validate the current files before a session opens.
# Exit code 0 = safe to start, 1 = do not start.
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # print to stdout at INFO so the preflight is readable in a terminal
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        # this raises if either file is unusable
        cfg = LiveConfig()
    except Exception as exc:
        # name the problem and refuse
        print(f"PREFLIGHT FAILED -- do not start the book\n  {exc}")
        raise SystemExit(1)
    # the headline
    print(f"PREFLIGHT OK\n  {cfg.summary()}")
    print(f"  assignment: {cfg.assignment_path}")
    print(f"  overrides : {cfg.overrides_path}"
          f"{'' if cfg.overrides_path.exists() else '  (absent -- normal)'}")
    print(f"  drop semantics: {DROP_SEMANTICS}")
    # show the names that are pulled, because that is the one you want to eyeball
    pulled = [s for s in cfg.symbols(quoting_only=False) if s not in cfg.symbols()]
    print(f"  not quoted ({len(pulled)}): {', '.join(pulled) or '-'}")
    # at startup there can be no orphans by definition, but print the line at a
    # fixed place so a preflight run after a mid-session restart shows them
    orph = cfg.orphans()
    print(f"  orphans ({len(orph)}): {', '.join(orph) or '- none'}")
