import math
from collections import deque
from mm_backtest import FEE_TOTAL_PCT


class MicrostructureMM:
    """Market maker built from O'Hara, Market Microstructure Theory (1998).

    Implements, with chapter references:
      Ch 3.3 Glosten-Milgrom : fair value = flow-conditional expectation
                               (imbalance-weighted microprice, not the mid)
      Ch 2.2 Stoll /
      Ch 2.3 Ho-Stoll        : inventory shifts PLACEMENT (skew), not width;
                               width carries the risk term gamma*sigma^2*tau
      Ch 2.3 Ho-Stoll        : spread decays as the horizon tau -> 0
      Ch 3.4 Easley-O'Hara   : adverse selection rises in size -> cut SIZE, not
                               just widen, when flow looks informed
      Ch 6.3 Easley-O'Hara   : absence of trade => less informed trading =>
                               TIGHTEN (opposite of Diamond-Verrecchia)
      Ch 7.1 viability       : if the required spread exceeds the market spread,
                               no viable quote exists -> quote nothing

    FLAGGED SIMPLIFICATIONS (production versions noted):
      * sigma is a rolling realised vol of the reconstructed mid. Production:
        two-scale estimator with microstructure-noise correction.
      * toxicity is a signed-volume imbalance ratio over a trade window as a
        cheap stand-in for GM's mu / PIN. Production: fit PIN or VPIN, or the
        OFI-conditioned toxicity model on your own markout labels.
      * Kyle's lambda is NOT estimated here. Production: regress mid changes on
        signed order flow per symbol-day and use lambda to size the repricing
        response and the toxicity term.
      * the Avellaneda-Stoikov base half-spread (1/gamma)*ln(1+gamma/kappa) is
        computed but weighted 0 by default -- kappa must be calibrated from your
        real resting-order fill outcomes before it means anything.
      * gamma is a free risk-aversion parameter, NOT calibrated. Sweep it.
    """
    """
    quiet_ms=2000 — this default is wrong for both your symbols, in opposite directions. 
    It should scale with the symbol's median inter-trade gap: MCB's is 5.6 s (so 2 s
     calls it "active" mid-gap when nothing is wrong), OGDC's is 0.4 s (so 2 s almost 
     never triggers). Something like 2–3× the symbol's median gap, computed from the 
     data, not a constant.    
     
     sigma_window=200, flow_window=50 — event-count windows, so their wall-clock meaning 
     differs wildly per symbol (200 events ≈ most of an hour on MCB, ≈ 2 minutes on OGDC). 
     Per-symbol they should be chosen to represent a comparable time horizon, or replaced 
     by time-based windows.
     
     gamma — a genuinely free risk-aversion parameter with no formula; sweep it per symbol 
     and pick by out-of-sample PnL/drawdown. kappa — calibrate from real resting-order fill 
     outcomes (already flagged; inert until then via as_base_weight=0). min_edge_pct — 
     business policy, not calibration: how much you insist on earning above cost. tick=0.01 — 
     the one true constant (PSX-wide). session_ms — per day, already passed in
    
    So the parameter set splits into four classes: universal constants (tick), 
    per-symbol calibrated from data (size, max_inv, quiet_ms, windows, later κ and λ), 
    free parameters to sweep (gamma, and the weightings), and policy (min_edge_pct, 
    fee scenario). The natural next artifact when you scale beyond two symbols is a 
    small per-symbol config table — symbol → calibrated parameters — generated by a 
    calibration script from each symbol's own history, which the ticker-stats work 
    you've already built is most of the way toward producing.
     
    """

    def __init__(self, size=50, max_inv=500, gamma=0.15, kappa=1.5,
                 session_ms=(0, 1), fee_pct=None, min_edge_pct=0.0,
                 sigma_window=200, flow_window=50, tick=0.01,
                 quiet_ms=2000, require_viable=True, as_base_weight=0.0):
        # Baseline quote size in shares (Ch 3.4: this gets cut when flow is toxic).
        self.size0 = size
        # Hard inventory cap in shares (a backstop; the skew is the real control).
        self.max_inv = max_inv
        # Risk aversion. Scales BOTH the inventory skew and the risk half-spread.
        self.gamma = gamma
        # Order-arrival intensity decay for the A-S base term (needs calibration).
        self.kappa = kappa
        # Session start/end in exchange-ms; defines the Ho-Stoll horizon tau.
        self.t0, self.t1 = session_ms
        # All-in per-side fee as a fraction of traded value (the spread floor).
        # Fee floor for quoting decisions. Defaults to the SAME schedule the
        # backtester charges on fills -- one source of truth. Pass explicitly
        # only to run what-if scenarios (e.g. MM-programme fee relief).
        self.fee_pct = FEE_TOTAL_PCT if fee_pct is None else fee_pct
        # Extra edge demanded above fees before quoting at all.
        self.min_edge_pct = min_edge_pct
        # Price grid.
        self.tick = tick
        # Gap (ms) with no trade after which we treat the market as quiet.
        self.quiet_ms = quiet_ms
        # If True, refuse to quote when the market spread cannot cover our cost.
        self.require_viable = require_viable
        # Weight on the A-S base half-spread; 0 until kappa is calibrated.
        self.as_base_weight = as_base_weight
        # Rolling mid history for the volatility estimate.
        self.mids = deque(maxlen=sigma_window)
        # Rolling signed trade volume for the toxicity estimate.
        self.flow = deque(maxlen=flow_window)
        # Current exchange time, updated by observe().
        self.now = self.t0
        # Exchange time of the most recent trade (for the quiet test).
        self.last_trade_ms = None
        # Rolling per-event return volatility.
        self.sigma = 0.0
        # Diagnostics: how often the viability gate refused to quote.
        self.stats = {"no_quote_unviable": 0, "quotes_made": 0}

    # ---- calibration state: called once per event by the backtester ---------
    def observe(self, kind, obj, ts_exch, mid):
        # Advance our clock so the Ho-Stoll horizon tau is current.
        self.now = ts_exch
        # Track the mid only when the book is two-sided.
        if mid is not None:
            self.mids.append(mid)
            # Need a minimum sample before a volatility estimate means anything.
            if len(self.mids) >= 20:
                m = list(self.mids)
                # Simple returns between consecutive observed mids.
                rets = [(m[i] - m[i - 1]) / m[i - 1] for i in range(1, len(m))
                        if m[i - 1] > 0]
                if rets:
                    mu = sum(rets) / len(rets)
                    var = sum((r - mu) ** 2 for r in rets) / len(rets)
                    # Per-event return volatility (NOT annualised; scale-free here).
                    self.sigma = math.sqrt(var)
        # Trades carry the direction signal Glosten-Milgrom conditions on.
        if kind == "T":
            side = getattr(obj, "aggressor_side", None)
            if side in ("BUY", "SELL"):
                # Signed volume: +buy, -sell.
                self.flow.append(float(obj.qty) * (1.0 if side == "BUY" else -1.0))
                # Reset the quiet clock.
                self.last_trade_ms = ts_exch

    # ---- derived microstructure quantities ---------------------------------
    def _toxicity(self):
        # No trades observed yet -> assume benign.
        if not self.flow:
            return 0.0
        # Net direction of recent flow.
        signed = sum(self.flow)
        # Total recent volume regardless of direction.
        gross = sum(abs(f) for f in self.flow)
        # |net| / gross in [0,1]: 0 = balanced two-way flow (uninformed),
        # 1 = one-directional sweep (the GM signature of informed trading).
        return abs(signed) / gross if gross > 0 else 0.0

    def _quiet(self):
        # No trade seen at all -> treat as quiet.
        if self.last_trade_ms is None:
            return True
        # Ch 6.3: a long gap since the last trade is evidence AGAINST an
        # information event, so it should tighten us, not widen us.
        return (self.now - self.last_trade_ms) > self.quiet_ms

    def _horizon(self):
        # Session length in ms, guarded against zero.
        span = max(self.t1 - self.t0, 1)
        # Ho-Stoll tau: 1.0 at the open, 0.0 at the flatten time. The risk
        # component decays with it, so the spread narrows into the close.
        return max(0.0, min(1.0, (self.t1 - self.now) / span))

    # ---- quoting -----------------------------------------------------------
    def quotes(self, bb, bq, ba, aq, pos):
        # No two-sided book with depth on both sides -> nothing to quote against.
        if bb is None or ba is None or bq <= 0 or aq <= 0:
            return {}
        # Bid share of top-of-book depth.
        imb = bq / (bq + aq)
        # Ch 3.3 proxy for the flow-conditional expectation: heavier bid depth
        # pulls fair value UP toward the ask. This replaces the naive mid.
        fair = ba * imb + bb * (1.0 - imb)
        # Ho-Stoll horizon.
        tau = self._horizon()
        # Per-unit inventory risk: risk aversion x variance x remaining horizon.
        inv_risk = self.gamma * (self.sigma ** 2) * tau
        # Ch 2.2/2.3: inventory SHIFTS the quote pair. Long -> shift down (sell
        # more eagerly, buy less); short -> shift up. Width is untouched.
        skew = inv_risk * pos * fair
        # The reservation price: our own indifference value, fair value less skew.
        reservation = fair - skew
        # Avellaneda-Stoikov base half-spread; inert until kappa is calibrated.
        as_base = (1.0 / self.gamma) * math.log(1.0 + self.gamma / self.kappa) \
            if self.gamma > 0 else 0.0
        # Half-spread component compensating inventory/price risk over tau.
        half_risk = 0.5 * inv_risk * fair
        # Current adverse-selection estimate from flow one-sidedness.
        tox = self._toxicity()
        # Ch 6.3: quiet market -> halve the adverse-selection charge (tighten).
        if self._quiet():
            tox *= 0.5
        # Adverse-selection half-spread: scales with toxicity and volatility.
        half_adverse = tox * (self.sigma * fair) * 2.0
        # Ch 7.1: the hard economic floor -- fees plus the edge we insist on.
        cost_floor = (self.fee_pct + self.min_edge_pct) * fair
        # Total half-spread: risk + adverse selection + (optional A-S base) + floor.
        half = half_risk + half_adverse + self.as_base_weight * as_base * fair + cost_floor
        # Never quote inside one tick.
        half = max(half, self.tick)
        # Ch 7.1 VIABILITY GATE: if the market's spread is narrower than the
        # spread we require, no profitable passive quote exists -> stand aside.
        if self.require_viable and (ba - bb) < 2.0 * half:
            self.stats["no_quote_unviable"] += 1
            return {}
        # Ch 3.4: informed flow prefers size, so cut OUR size when flow is toxic.
        size = self.size0 * (0.5 if tox > 0.5 else 1.0)
        size = max(1.0, round(size))
        out = {}
        # Bid unless we are already at the long cap.
        if pos < self.max_inv:
            # Floor onto the tick grid so rounding never makes us more aggressive.
            px = math.floor((reservation - half) / self.tick) * self.tick
            # Post-only clip: stay at least one tick inside the ask.
            px = min(px, ba - self.tick)
            out["BUY"] = (round(px, 2), size)
        # Offer unless we are already at the short cap.
        if pos > -self.max_inv:
            # Ceil onto the tick grid (again, never more aggressive).
            px = math.ceil((reservation + half) / self.tick) * self.tick
            # Post-only clip: stay at least one tick outside the bid.
            px = max(px, bb + self.tick)
            out["SELL"] = (round(px, 2), size)
        if out:
            self.stats["quotes_made"] += 1
        return out