import math
from collections import deque
from mm_backtest import FEE_TOTAL_PCT


class MicrostructureMM:
    """Market maker built from O'Hara, Market Microstructure Theory (1998).

    Implements, with chapter references:
      Ch 3.3 Glosten-Milgrom : fair value = flow-conditional expectation
                               (imbalance-weighted microprice, not the mid)
      Ch 2.2 Stoll /
      Ch 2.3 Ho-Stoll        : inventory shifts PLACEMENT (skew), not width;
                               width carries the risk term gamma*sigma^2*tau
      Ch 2.3 Ho-Stoll        : spread decays as the horizon tau -> 0
      Ch 3.4 Easley-O'Hara   : adverse selection rises in size -> cut SIZE, not
                               just widen, when flow looks informed
      Ch 6.3 Easley-O'Hara   : absence of trade => less informed trading =>
                               TIGHTEN (opposite of Diamond-Verrecchia)
      Ch 7.1 viability       : if the required spread exceeds the market spread,
                               no viable quote exists -> quote nothing

    FLAGGED SIMPLIFICATIONS (production versions noted):
      * sigma is a rolling realised vol of the reconstructed mid. Production:
        two-scale estimator with microstructure-noise correction.
      * toxicity is a signed-volume imbalance ratio over a trade window as a
        cheap stand-in for GM's mu / PIN. Production: fit PIN or VPIN, or the
        OFI-conditioned toxicity model on your own markout labels.
      * Kyle's lambda is NOT estimated here. Production: regress mid changes on
        signed order flow per symbol-day and use lambda to size the repricing
        response and the toxicity term.
      * the Avellaneda-Stoikov base half-spread (1/gamma)*ln(1+gamma/kappa) is
        computed but weighted 0 by default -- kappa must be calibrated from your
        real resting-order fill outcomes before it means anything.
      * gamma is a free risk-aversion parameter, NOT calibrated. Sweep it.
    """
    """
    quiet_ms=2000 — this default is wrong for both your symbols, in opposite directions. 
    It should scale with the symbol's median inter-trade gap: MCB's is 5.6 s (so 2 s
     calls it "active" mid-gap when nothing is wrong), OGDC's is 0.4 s (so 2 s almost 
     never triggers). Something like 2–3× the symbol's median gap, computed from the 
     data, not a constant.    
     
     sigma_window=200, flow_window=50 — event-count windows, so their wall-clock meaning 
     differs wildly per symbol (200 events ≈ most of an hour on MCB, ≈ 2 minutes on OGDC). 
     Per-symbol they should be chosen to represent a comparable time horizon, or replaced 
     by time-based windows.
     
     gamma — a genuinely free risk-aversion parameter with no formula; sweep it per symbol 
     and pick by out-of-sample PnL/drawdown. kappa — calibrate from real resting-order fill 
     outcomes (already flagged; inert until then via as_base_weight=0). min_edge_pct — 
     business policy, not calibration: how much you insist on earning above cost. tick=0.01 — 
     the one true constant (PSX-wide). session_ms — per day, already passed in
    
    So the parameter set splits into four classes: universal constants (tick), 
    per-symbol calibrated from data (size, max_inv, quiet_ms, windows, later κ and λ), 
    free parameters to sweep (gamma, and the weightings), and policy (min_edge_pct, 
    fee scenario). The natural next artifact when you scale beyond two symbols is a 
    small per-symbol config table — symbol → calibrated parameters — generated by a 
    calibration script from each symbol's own history, which the ticker-stats work 
    you've already built is most of the way toward producing.
     
    """

    def __init__(self, size=50, max_inv=500, gamma=0.15, kappa=1.5,
                 session_ms=(0, 1), fee_pct=None, min_edge_pct=0.0,
                 flow_window=50, tick=0.01,
                 quiet_ms=2000, require_viable=True, as_base_weight=0.0,
                 improve_ticks=1.0, size_notional=None, tol_ticks=0.0, vol_alpha=0.05,
                 # session_scale is REQUIRED, keyword-only: no default -> a missing
                 # value raises TypeError at construction instead of silently
                 # skewing on a wrong scale.
                 # use_microprice=False -> quote around plain mid (neutral, like
                 # naive); it exists to test/disable the microprice, the confirmed
                 # driver of the short drift.
                 # soft_inv=N -> once |pos|>N, stop quoting the side that ADDS to the
                 # position (pull that quote) so fills can only reduce it. None
                 # disables the band.
                 *, session_scale, use_microprice=True, soft_inv=None):
        # Baseline quote size in shares (Ch 3.4: this gets cut when flow is toxic).
        self.size0 = size
        # Hard inventory cap in shares (a backstop; the skew is the real control).
        self.max_inv = max_inv
        # Soft inventory band in shares: once |pos| exceeds it we stop quoting the
        # side that ADDS to the position, so fills can only reduce it. None disables
        # the band. Sweep {100, 150, 200}.
        self.soft_inv = soft_inv
        # Directional-pricing toggle: True = imbalance microprice (Ch 3.3); False =
        # plain mid (neutral, like naive). The microprice is the confirmed cause of
        # the short drift, so this exists to test/disable it.
        self.use_microprice = use_microprice
        # Risk aversion. Scales BOTH the inventory skew and the risk half-spread.
        self.gamma = gamma
        # Dimensional bridge (units 1/PKR) scaling the inventory skew from PKR
        # variance to PKR price; gamma is treated as dimensionless in the skew, so
        # THIS carries the dimension. CALIBRATED, not free: back-solved per symbol so
        # skew at max inventory ~ 1x median spread (derived PPL~7.6, UBL~3.9). SWEEP
        # it {0.25, 0.5, 1, 2}x the derived value -- do NOT trust the default.
        self.session_scale = session_scale
        # Order-arrival intensity decay for the A-S base term (needs calibration).
        self.kappa = kappa
        # Session start/end in exchange-ms; defines the Ho-Stoll horizon tau.
        self.t0, self.t1 = session_ms
        # All-in per-side fee as a fraction of traded value (the spread floor).
        # Fee floor for quoting decisions. Defaults to the SAME schedule the
        # backtester charges on fills -- one source of truth. Pass explicitly
        # only to run what-if scenarios (e.g. MM-programme fee relief).
        self.fee_pct = FEE_TOTAL_PCT if fee_pct is None else fee_pct
        # Extra edge demanded above fees before quoting at all.
        self.min_edge_pct = min_edge_pct
        # Price grid.
        self.tick = tick
        # Gap (ms) with no trade after which we treat the market as quiet.
        self.quiet_ms = quiet_ms
        # If True, refuse to quote when the market spread cannot cover our cost.
        self.require_viable = require_viable
        # Weight on the A-S base half-spread; 0 until kappa is calibrated.
        self.as_base_weight = as_base_weight

        # Rolling signed trade volume for the toxicity estimate.
        self.flow = deque(maxlen=flow_window)
        # Current exchange time, updated by observe().
        self.now = self.t0
        # Exchange time of the most recent trade (for the quiet test).
        self.last_trade_ms = None
        # Rolling per-event return volatility.
        self.sigma = 0.0

        # Placement: quote at most this many ticks inside the prevailing touch.
        self.improve_ticks = improve_ticks
        # PKR per quote (overrides share-count sizing when set).
        self.size_notional = size_notional
        # Pegging tolerance in ticks (0 = off).
        self.tol_ticks = tol_ticks
        # EMA decay for the volatility estimator (0.05 ~ 13.5-move half-life).
        self.vol_alpha = vol_alpha
        # Last observed mid (EMA vol updates only on actual mid moves).
        self.last_mid = None
        # Running EMA of squared mid returns.
        self.ema_var = 0.0
        # Our last DESIRED quotes, for the pegging hysteresis.
        self.last_desired = {}

        # Diagnostics: how often the viability gate refused to quote.
        self.stats = {"no_quote_unviable": 0, "quotes_made": 0}

    # ---- calibration state: called once per event by the backtester ---------
    def observe(self, kind, obj, ts_exch, mid):
        # Advance our clock so the Ho-Stoll horizon tau is current.
        self.now = ts_exch

        # EMA volatility: O(1) per event, updated only when the mid actually
        # moves (unchanged mids carry no volatility information). Replaces the
        # O(window) recompute over the mids deque.
        if mid is not None:
            if self.last_mid is not None and mid != self.last_mid and self.last_mid > 0:
                # Simple return since the last DIFFERENT mid.
                ret = (mid - self.last_mid) / self.last_mid
                # Seed on first move; RiskMetrics-style EMA thereafter.
                if self.ema_var == 0.0:
                    self.ema_var = ret * ret
                else:
                    self.ema_var = self.vol_alpha * ret * ret + (1.0 - self.vol_alpha) * self.ema_var
                self.sigma = math.sqrt(self.ema_var)
            self.last_mid = mid

        # Trades carry the direction signal Glosten-Milgrom conditions on.
        if kind == "T":
            side = getattr(obj, "aggressor_side", None)
            if side in ("BUY", "SELL"):
                # Signed volume: +buy, -sell.
                self.flow.append(float(obj.qty) * (1.0 if side == "BUY" else -1.0))
                # Reset the quiet clock.
                self.last_trade_ms = ts_exch

    # ---- derived microstructure quantities ---------------------------------
    def _toxicity(self):
        # No trades observed yet -> assume benign.
        if not self.flow:
            return 0.0
        # Net direction of recent flow.
        signed = sum(self.flow)
        # Total recent volume regardless of direction.
        gross = sum(abs(f) for f in self.flow)
        # |net| / gross in [0,1]: 0 = balanced two-way flow (uninformed),
        # 1 = one-directional sweep (the GM signature of informed trading).
        return abs(signed) / gross if gross > 0 else 0.0

    def _quiet(self):
        # No trade seen at all -> treat as quiet.
        if self.last_trade_ms is None:
            return True
        # Ch 6.3: a long gap since the last trade is evidence AGAINST an
        # information event, so it should tighten us, not widen us.
        return (self.now - self.last_trade_ms) > self.quiet_ms

    def _horizon(self):
        # Session length in ms, guarded against zero.
        span = max(self.t1 - self.t0, 1)
        # Ho-Stoll tau: 1.0 at the open, 0.0 at the flatten time. The risk
        # component decays with it, so the spread narrows into the close.
        return max(0.0, min(1.0, (self.t1 - self.now) / span))

    # ---- quoting -----------------------------------------------------------
    def quotes(self, bb, bq, ba, aq, pos):
        # No two-sided book with depth on both sides -> nothing to quote against.
        if bb is None or ba is None or bq <= 0 or aq <= 0:
            return {}
        # Bid share of top-of-book depth.
        imb = bq / (bq + aq)
        # Ch 3.3 microprice: heavier bid depth pulls fair value UP toward the ask.
        # This is DIRECTIONAL -- the confirmed cause of the short drift (micro sells
        # into ask-heavy books, buys into bid-heavy ones). use_microprice=False
        # quotes around the plain mid, like naive, to remove the lean.
        if self.use_microprice:
            fair = ba * imb + bb * (1.0 - imb)
        else:
            fair = 0.5 * (bb + ba)
        # Ho-Stoll horizon.
        tau = self._horizon()
        # Per-unit inventory risk: risk aversion x variance x remaining horizon.
        inv_risk = self.gamma * (self.sigma ** 2) * tau
        # --- inventory skew, corrected to PKR variance (Ho-Stoll / A-S) --------
        # BUG FIX: self.sigma is a per-event FRACTIONAL-return vol (~1e-4). The old
        # skew inv_risk*pos*fair therefore used sigma^2 ~ 1e-8 and produced ~7.5e-5
        # PKR at full inventory -- under 1/100th of a tick, so inventory control was
        # inert. Convert sigma to a PKR PRICE vol before squaring.
        sigma_p = self.sigma * fair
        # Remaining inventory variance over the session: PKR-variance x a calibrated
        # dimensional bridge (units 1/PKR) x the remaining-time fraction. LINEAR in
        # tau -- A-S is linear in time-to-horizon and tau already encodes (T-now)/span.
        remaining_var = (sigma_p ** 2) * self.session_scale * tau
        # Inventory in LOTS (pos / base clip), not raw shares, so the lean scales with
        # how many clips we are from flat. session_scale was calibrated against this.
        pos_lots = pos / self.size0
        # Ch 2.2/2.3: inventory SHIFTS the quote pair. Long (pos>0) -> skew>0 ->
        # reservation below fair -> sell eagerly / buy less. Width left untouched.
        skew = self.gamma * remaining_var * pos_lots
        # The reservation price: our own indifference value, fair value less skew.
        reservation = fair - skew
        # Avellaneda-Stoikov base half-spread; inert until kappa is calibrated.
        as_base = (1.0 / self.gamma) * math.log(1.0 + self.gamma / self.kappa) \
            if self.gamma > 0 else 0.0
        # Half-spread component compensating inventory/price risk over tau.
        half_risk = 0.5 * inv_risk * fair
        # Current adverse-selection estimate from flow one-sidedness.
        tox = self._toxicity()
        # Ch 6.3: quiet market -> halve the adverse-selection charge (tighten).
        if self._quiet():
            tox *= 0.5
        # Adverse-selection half-spread: scales with toxicity and volatility.
        half_adverse = tox * (self.sigma * fair) * 2.0
        # Ch 7.1: the hard economic floor -- fees plus the edge we insist on.
        cost_floor = (self.fee_pct + self.min_edge_pct) * fair
        # Total half-spread: risk + adverse selection + (optional A-S base) + floor.
        half = half_risk + half_adverse + self.as_base_weight * as_base * fair + cost_floor
        # Never quote inside one tick.
        half = max(half, self.tick)
        # Ch 7.1 VIABILITY GATE: if the market's spread is narrower than the
        # spread we require, no profitable passive quote exists -> stand aside.
        if self.require_viable and (ba - bb) < 2.0 * half:
            self.stats["no_quote_unviable"] += 1
            return {}

        # Ch 3.4: informed flow prefers size, so cut OUR size when flow is toxic.

        # WIDE-MARKET PLACEMENT (the key change for KTML-class names): the gate
        # above checked economic viability with the COST-based half. For placement,
        # never quote tighter than one improve_ticks inside the prevailing touch --
        # on a 53bps market, capture ~the full spread instead of compressing it
        # to our 35bps floor and donating the difference.
        mkt_half = (ba - bb) / 2.0
        half = max(half, mkt_half - self.improve_ticks * self.tick)
        # NOTIONAL SIZING: 50 shares is 2.8k PKR on KTML but 20k on MCB. Fix the
        # PKR-at-risk per quote instead; fall back to share count if unset.
        base_size = (self.size_notional / fair) if self.size_notional else self.size0
        size = base_size * (0.5 if tox > 0.5 else 1.0)

        size = max(1.0, round(size))
        out = {}
        # Bid unless long at the hard cap OR already long past the soft band
        # (past +soft_inv we stop buying so fills can only reduce a long).
        if pos < self.max_inv and (self.soft_inv is None or pos < self.soft_inv):
            # Floor onto the tick grid so rounding never makes us more aggressive.
            px = math.floor((reservation - half) / self.tick) * self.tick
            # Post-only clip: stay at least one tick inside the ask.
            px = min(px, ba - self.tick)
            out["BUY"] = (round(px, 2), size)
        # Offer unless short at the hard cap OR already short past the soft band
        # (past -soft_inv we stop selling so only the bid remains -> we cover).
        if pos > -self.max_inv and (self.soft_inv is None or pos > -self.soft_inv):
            # Ceil onto the tick grid (again, never more aggressive).
            px = math.ceil((reservation + half) / self.tick) * self.tick
            # Post-only clip: stay at least one tick outside the bid.
            px = max(px, bb + self.tick)
            out["SELL"] = (round(px, 2), size)

        # QUOTE PEGGING (burst-flow names): hold the previous desired quote until
        # the ideal drifts >= tol_ticks. Returns the FULL desired state (our
        # protocol: an omitted side means cancel) and tracks only our own last
        # DESIRE -- never a claim about what rests on the exchange.
        if self.tol_ticks > 0:
            tol = self.tol_ticks * self.tick
            pegged = {}
            for s_, w_ in out.items():
                prev = self.last_desired.get(s_)
                # Close enough to the previous desire -> hold it (keep queue position).
                if prev is not None and abs(w_[0] - prev[0]) < tol and w_[1] == prev[1]:
                    pegged[s_] = prev
                else:
                    pegged[s_] = w_
            out = pegged
            self.last_desired = dict(out)
        if out:
            self.stats["quotes_made"] += 1
        return out
