"""The per-symbol live config: which names quote, and how hard they lean.

PROVENANCE. This is `existing_mm_live/live_config.py` moved into the production
tree, with paths injected instead of imported from `config_pk`, and with three
changes noted as CHANGED below. Everything else -- the two-file split, the
asymmetric failure policy, the torn-read protection, the orphan rule, the DROP
semantics -- is that module's design and its reasoning is kept verbatim where it
was already right. There should be exactly one implementation of this; a second
one that drifts is how a name ends up quoting a setting nobody chose.

TWO FILES, NOT ONE:
  ASSIGNMENT  config_assignment_YYYYMMDD_HHMM.csv -- machine-generated by
              build_config_assignment.py, 113 rows, NEVER hand-edited.
  OVERRIDES   live_overrides.csv -- hand-edited, sparse (usually 0-3 rows),
              wins over the assignment for the symbols it names.
Why: during an earnings halt you are editing a file under time pressure. A
3-row file you can read at a glance is a different risk from a 113-row
machine-generated file where a stray keystroke on the wrong line silently
changes a name you never looked at. It also means the next refit can drop a new
assignment in without clobbering a manual intervention that is still live.

FAILURE POLICY -- deliberately asymmetric:
  AT STARTUP   a bad file is FATAL. There is no last-good config to fall back
               to, and starting on engine defaults would quote 113 names on a
               config nobody chose. Refuse to start.
  ON RELOAD    a bad file is IGNORED and the last good config stays live, with
               a loud log line. Dropping the whole book because someone saved a
               CSV mid-edit is worse than running the previous config for
               another three minutes.

TORN READS. The file may be read while an editor is writing it. This module
reads the bytes in one shot and parses from memory, so a half-written file
fails validation and is rejected rather than half-applied. The assignment is
written with a temp file plus os.replace(), so that one is atomic already; the
overrides file is typed into an editor at 14:00 and is the one this protects.

ABSENCE IS NOT AN INSTRUCTION. If a symbol stops appearing in the assignment it
keeps running on its last setting. Stopping a name requires writing DROP
against it. A missing row has too many innocent causes -- a filtered export, a
copy-paste that lost lines, an editor truncating a save -- to be read as "stop
trading this". The cost of that rule is that a name a refit legitimately
dropped would keep quoting unnoticed, so every such symbol is re-warned on
EVERY reload, appears in summary(), and is listed by the preflight.

--- CHANGED from live_config.py, 2026-09-16 -------------------------------
1. THE ENGINE NUMBERS ARE READ FROM THE FILE AND CROSS-CHECKED, not re-derived
   from the label. live_config.py's LABELS table carried its own copy of
   (ticks, threshold) per label, with a comment that it "must stay identical to
   build_config_assignment.py's PARAMS" -- a hand-maintained duplicate of
   numbers that already travel in the CSV as `skew_ticks` and `skew_thresh`.
   If a refit ever moved the lean to three ticks, the CSV would say 3.0, the
   table would still say 2.0, and the engine would quote the old lean with no
   error anywhere. So: read the columns, and refuse to start if they disagree
   with what this code believes the label means. Neither source is trusted over
   the other, because there is no way to tell which one is stale.
2. A PRE-2026-09-15 TWO-BUCKET FILE IS NAMED IN THE ERROR. Those files have no
   skew columns and label the lean plain "QT_2t", so they were already rejected
   -- but by a message about an unknown setting, which does not tell you that
   you pointed the engine at a superseded assignment.
---------------------------------------------------------------------------
"""
# stdlib only on the live path: no pandas, so a CSV parse cannot pull in a
# heavy import or a version-dependent dtype coercion mid-session
import csv
import hashlib
import io
import logging
import threading
import time
from pathlib import Path
from typing import Dict, Optional, Set, Tuple

# how often the live loop should call refresh()
REFRESH_SECONDS = 180

# ---------------------------------------------------------------------------
# THE LABEL TABLE
# ---------------------------------------------------------------------------
# micro_mm's OWN constructor default for queue_skew_thresh. Used as the
# threshold whenever the lean is off.
#
# WHY NOT 0.0, AND WHY NOT NaN. build_config_assignment.py writes NaN (a blank
# cell) for a setting where the threshold is meaningless. Do not pass NaN into
# the engine -- every comparison against NaN is False, so it would happen to
# work today and break silently the first time someone writes `if thresh <= x`
# instead of `>`. And do not pass 0.0 either: zero is the MOST-firing value
# possible, so if the `queue_skew_ticks != 0` gate were ever removed or the
# threshold read somewhere else, 0.0 would fire on every bid-heavy book.
# micro_mm's own default is inert while ticks == 0 and conservative if it ever
# stops being inert.
DEFAULT_THRESH = 0.15

# label -> what the ASSIGNMENT FILE should contain for it.
# None means the generator writes a blank cell, which it does wherever the
# number is meaningless for that setting.
FILE_PARAMS: Dict[str, Tuple[Optional[float], Optional[float]]] = {
    # the lean, firing once the book is 0.15 past balanced
    "QT_2t@15": (2.0, 0.15),
    # the same lean, firing less often
    "QT_2t@20": (2.0, 0.20),
    # lean off: the generator writes 0.0 ticks and a blank threshold
    "OBI": (0.0, None),
    # not quoted: the generator writes both cells blank
    "DROP": (None, None),
}

# label -> what the ENGINE is given: (queue_skew_ticks, queue_skew_thresh,
# quote?). Distinct from FILE_PARAMS because "blank in the CSV" and "what
# micro_mm should be constructed with" are different questions -- see
# DEFAULT_THRESH above.
ENGINE_PARAMS: Dict[str, Tuple[float, float, bool]] = {
    # the incumbent lean
    "QT_2t@15": (2.0, 0.15, True),
    # the higher-trigger lean
    "QT_2t@20": (2.0, 0.20, True),
    # lean off: zero ticks, which micro_mm documents as byte-identical to the
    # feature being absent
    "OBI": (0.0, DEFAULT_THRESH, True),
    # not quoted -- see DROP_SEMANTICS
    "DROP": (0.0, DEFAULT_THRESH, False),
}

# accepted spellings for the same thing, so a hand-edited override file can say
# something a human would actually type at 14:00 under pressure
ALIASES = {
    "LEAN": "QT_2t@15", "LEAN15": "QT_2t@15", "QT_2T@15": "QT_2t@15",
    "LEAN20": "QT_2t@20", "QT_2T@20": "QT_2t@20",
    "OFF": "OBI", "LEANOFF": "OBI", "LEAN_OFF": "OBI",
    "STOP": "DROP", "PULL": "DROP", "HALT": "DROP",
}

# CHANGED 2026-09-16 (3): resolve every spelling case-insensitively, INCLUDING
# the canonical labels themselves.
#
# live_config.py did `ALIASES.get(label.upper(), label)` and then tested the
# result against LABELS. That works for the aliases and for a correctly-cased
# canonical label -- but "OBI" and "DROP" are not IN the alias table, so an
# operator who typed `drop` or `obi` in lower case got the whole overrides file
# rejected. Those are the exact spellings the assignment file uses, so they are
# the likeliest thing to be copied across, and it fails at 14:00 on the one
# edit that matters. Built once here so the two tables cannot drift apart.
_RESOLVE = {label.upper(): label for label in ENGINE_PARAMS}
# the aliases layer on top; an alias may not shadow a canonical label
_RESOLVE.update(ALIASES)

# the columns this module reads from the assignment
COL_SYMBOL = "symbol"
COL_ASSIGNED = "assigned_config"
COL_TICKS = "skew_ticks"
COL_THRESH = "skew_thresh"

# ---------------------------------------------------------------------------
# DROP SEMANTICS -- there is no safe default, so it is named here.
# ---------------------------------------------------------------------------
#   "no_add"  stop quoting the side that would ADD to the position; keep quoting
#             the reducing side so inventory works off passively. This is what
#             "pull the name, I don't want new risk into earnings" usually means.
#   "flat"    stop quoting entirely and hold whatever is on the book. Only right
#             if something else is responsible for the position.
#   "cross"   cross out immediately at market. Guarantees flat, pays the spread
#             (5.3-79 bps depending on the name -- see the hedge cost work).
# CHOSEN 2026-09-15: "no_add". It needs no engine change -- micro_mm's soft_inv
# band already implements it, and params_for() emits soft_inv=0 to switch it on.
# Note what "no_add" does NOT do: it stops you getting deeper, it does not get
# you out. If the reason for pulling a name is that you want to be FLAT before
# an announcement rather than merely not-longer, no_add will not achieve that
# and "cross" is the only setting that will.
DROP_SEMANTICS = "no_add"

# module logger; the live app attaches its own handler
log = logging.getLogger("psx_config")


class ConfigError(Exception):
    """A config file is unusable. Fatal at startup, caught on reload."""


def _read_bytes(path: Path) -> bytes:
    # single read() so an editor writing the file cannot give us two halves
    # from two different versions -- we get a coherent file or a broken one
    with open(path, "rb") as fh:
        return fh.read()


def _decode(raw: bytes, path: Path) -> str:
    # decode strictly: a mojibake file is a corrupt file, not something to
    # coerce, and the platform's default encoding is not a property of the file
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ConfigError(f"{path.name}: not valid UTF-8 ({exc})")


def _number(raw, path: Path, line_no: int, symbol: str,
            column: str) -> Optional[float]:
    """A numeric cell, where a blank legitimately means 'not applicable'."""
    # strip; blank is a real value in these columns
    text = (raw or "").strip()
    # DROP has neither number; lean off has no threshold
    if not text:
        return None
    # anything non-numeric is a typo
    try:
        return float(text)
    except ValueError:
        raise ConfigError(f"{path.name} line {line_no}: {symbol} has "
                          f"{column}={text!r}, which is not a number")


def _same(got: Optional[float], want: Optional[float]) -> bool:
    """Float comparison that treats None as a value in its own right."""
    # both absent
    if got is None and want is None:
        return True
    # one absent, one not
    if got is None or want is None:
        return False
    # close enough for a CSV round trip of 0.2 or 2.0
    return abs(got - want) < 1e-9


def _parse_assignment(raw: bytes, path: Path) -> Dict[str, str]:
    """The machine-generated assignment -> {symbol: label}. Raises ConfigError."""
    # parse from memory, never from the live file handle
    reader = csv.DictReader(io.StringIO(_decode(raw, path)))
    # a file with no header at all is corrupt, not empty
    if reader.fieldnames is None:
        raise ConfigError(f"{path.name}: no header row")
    # what the file has
    cols = set(reader.fieldnames)
    # every column this module needs
    missing = [c for c in (COL_SYMBOL, COL_ASSIGNED, COL_TICKS, COL_THRESH)
               if c not in cols]
    # refuse, and say what the file actually is
    if missing:
        # CHANGED 2026-09-16: name the likeliest cause rather than leaving the
        # operator to work out why a valid-looking file was rejected
        hint = ("  This looks like a pre-2026-09-15 TWO-BUCKET file: those "
                "carried no skew_ticks/skew_thresh and labelled the lean plain "
                "'QT_2t'. That assignment was superseded by the three-bucket "
                "rule -- point the engine at a three-bucket file."
                if COL_TICKS in missing else "")
        raise ConfigError(f"{path.name}: missing column(s) {missing}; "
                          f"has {sorted(cols)}.{hint}")
    # accumulate, so a bad row aborts the file rather than half-applying it
    out: Dict[str, str] = {}
    # row 1 is the header
    for line_no, row in enumerate(reader, start=2):
        # the symbol, normalised
        symbol = (row.get(COL_SYMBOL) or "").strip().upper()
        # a trailing blank line is not an error
        if not symbol:
            continue
        # a comment row, by the same rule the overrides file uses
        if symbol.startswith("#"):
            continue
        # a symbol listed twice means two conflicting instructions
        if symbol in out:
            raise ConfigError(
                f"{path.name} line {line_no}: {symbol} appears more than once")
        # the label as written
        label = (row.get(COL_ASSIGNED) or "").strip()
        # an empty label is a half-finished edit
        if not label:
            raise ConfigError(f"{path.name} line {line_no}: {symbol} has an "
                              f"empty {COL_ASSIGNED}")
        # resolve an alias if one was used
        label = _RESOLVE.get(label.upper(), label)
        # HARD FAILURE on an unknown label. A typo must never fall through to a
        # default: a name quietly running the wrong config is invisible until
        # the P&L attribution months later.
        if label not in ENGINE_PARAMS:
            raise ConfigError(
                f"{path.name} line {line_no}: {symbol} has unknown setting "
                f"{label!r}; valid: {sorted(ENGINE_PARAMS)} "
                f"(aliases: {sorted(ALIASES)})")
        # CHANGED 2026-09-16: the engine numbers are in the file, so read them
        # and check them rather than re-deriving from the label
        ticks = _number(row.get(COL_TICKS), path, line_no, symbol, COL_TICKS)
        thresh = _number(row.get(COL_THRESH), path, line_no, symbol, COL_THRESH)
        # what this code believes the label means
        want_ticks, want_thresh = FILE_PARAMS[label]
        # a disagreement means either the generator changed and this table did
        # not, or the file was hand-edited. Neither is recoverable here: there
        # is no way to tell which of the two is the stale one.
        if not (_same(ticks, want_ticks) and _same(thresh, want_thresh)):
            raise ConfigError(
                f"{path.name} line {line_no}: {symbol} is {label}, which this "
                f"engine reads as ticks={want_ticks} thresh={want_thresh}, but "
                f"the file says ticks={ticks} thresh={thresh}. Either the "
                f"assignment rule changed and FILE_PARAMS/ENGINE_PARAMS here "
                f"were not updated, or the file was edited by hand.")
        # accept the row
        out[symbol] = label
    # an assignment with no rows is corrupt -- it would orphan the whole book
    if not out:
        raise ConfigError(f"{path.name}: parsed zero rows")
    # the whole file, or nothing
    return out


def _parse_overrides(raw: bytes, path: Path) -> Dict[str, str]:
    """The hand-edited overrides -> {symbol: label}. ALL OF IT, OR NONE OF IT."""
    # parse from memory
    reader = csv.DictReader(io.StringIO(_decode(raw, path)))
    # an empty file is normal for this one
    if reader.fieldnames is None:
        return {}
    # what the file has
    cols = set(reader.fieldnames)
    # the symbol column is mandatory
    if COL_SYMBOL not in cols:
        raise ConfigError(f"{path.name}: no '{COL_SYMBOL}' column; "
                          f"has {sorted(cols)}")
    # the overrides file names its column `config`; accept the assignment's
    # spelling too, since someone will paste a row across at some point
    label_col = (COL_ASSIGNED if COL_ASSIGNED in cols
                 else ("config" if "config" in cols else None))
    # without a label column there is nothing to apply
    if label_col is None:
        raise ConfigError(f"{path.name}: no 'config' or '{COL_ASSIGNED}' "
                          f"column; has {sorted(cols)}")
    # accumulate
    out: Dict[str, str] = {}
    # row 1 is the header
    for line_no, row in enumerate(reader, start=2):
        # the symbol, normalised
        symbol = (row.get(COL_SYMBOL) or "").strip().upper()
        # a blank line at the end of a hand-edited file is not an error
        if not symbol:
            continue
        # COMMENT ROWS. A line whose symbol cell starts with '#' is a note, not
        # a symbol. This exists so the operator can record WHY a name was
        # pulled at 14:00 in the same file as the instruction -- otherwise that
        # reason lives only in someone's head and post-trade cannot reconstruct
        # the day.
        if symbol.startswith("#"):
            continue
        # two instructions for one name
        if symbol in out:
            raise ConfigError(
                f"{path.name} line {line_no}: {symbol} appears more than once")
        # the label as written
        label = (row.get(label_col) or "").strip()
        # an empty label is a half-finished edit -- refuse the file
        if not label:
            raise ConfigError(f"{path.name} line {line_no}: {symbol} has an "
                              f"empty {label_col}")
        # resolve an alias
        label = _RESOLVE.get(label.upper(), label)
        # ONE BAD VALUE REJECTS THE WHOLE FILE. Applying the rows above a typo
        # and not the rows below leaves the book in a state no file describes.
        if label not in ENGINE_PARAMS:
            raise ConfigError(
                f"{path.name} line {line_no}: {symbol} has unknown setting "
                f"{label!r}; valid: {sorted(ENGINE_PARAMS)} "
                f"(aliases: {sorted(ALIASES)})")
        # accept
        out[symbol] = label
    # every row parsed
    return out


class LiveConfig:
    """Hot-reloadable per-symbol config. One instance; call refresh() on a timer.

    PATHS ARE INJECTED. live_config.py imported RESULTS_ROOT from config_pk and
    named the assignment file as a module constant. That is right for a module
    living in the research tree beside its data; it is wrong here, because the
    live engine must not import anything that knows where the backtest keeps
    its results.
    """

    def __init__(self, assignment_path, overrides_path=None):
        # where the machine-generated baseline lives
        self.assignment_path = Path(assignment_path)
        # where the sparse hand-edited interventions live; may legitimately
        # not exist
        self.overrides_path = (Path(overrides_path)
                               if overrides_path is not None else None)
        # the last config that parsed cleanly: {symbol: label}
        self._live: Dict[str, str] = {}
        # content hashes of the last accepted files, so an unchanged file is a
        # no-op -- cheaper and more honest than mtime, which an editor or a
        # copy can bump without changing anything
        self._hashes: Dict[str, str] = {}
        # which symbols are currently coming from the override file
        self._overridden: Set[str] = set()
        # symbols still live but no longer in the assignment, carried forward
        # at their last setting and re-warned on every reload
        self._orphans: Set[str] = set()
        # guards the swap against a reload landing mid-read from the quoting
        # thread
        self._lock = threading.RLock()
        # when the last successful load finished
        self.last_good_ts: Optional[float] = None
        # how many consecutive reloads have failed, for alerting
        self.consecutive_failures = 0
        # STARTUP: load once, and let any error propagate. There is nothing in
        # memory to fall back to, so a bad file here must stop the launch
        # rather than start 113 names on a config nobody chose this morning.
        self._load()

    # ---- loading ----------------------------------------------------------
    def _load(self) -> Dict[str, Tuple[str, str]]:
        """Read both files and swap them in. Returns {symbol: (old, new)}."""
        # the baseline must exist
        if not self.assignment_path.exists():
            raise ConfigError(f"assignment not found: {self.assignment_path}")
        # read it whole
        raw_a = _read_bytes(self.assignment_path)
        # the override file is optional by design
        raw_o = (_read_bytes(self.overrides_path)
                 if self.overrides_path is not None
                 and self.overrides_path.exists() else b"")
        # content hashes of what we just read
        hashes = {"assignment": hashlib.sha1(raw_a).hexdigest(),
                  "overrides": hashlib.sha1(raw_o).hexdigest()}
        # nothing changed since the last accepted load -> no work, no log spam
        if hashes == self._hashes and self._live:
            return {}
        # parse the baseline (raises on any problem)
        merged = _parse_assignment(raw_a, self.assignment_path)
        # parse the overrides, if there are any
        overridden: Set[str] = set()
        if raw_o.strip():
            # every row, or none
            override = _parse_overrides(raw_o, self.overrides_path)
            # an override naming a symbol not in the assignment is a typo, not
            # a new name -- the universe is decided by the refit, not at 14:00
            unknown = sorted(set(override) - set(merged))
            if unknown:
                raise ConfigError(f"{self.overrides_path.name}: symbols not in "
                                  f"the assignment: {unknown}")
            # overrides win
            merged.update(override)
            # remember which, so a log line can say where a setting came from
            overridden = set(override)
        # ABSENCE NEVER CHANGES BEHAVIOUR. A symbol that has dropped out of the
        # assignment keeps whatever setting it is already running. Stopping a
        # name requires writing DROP against it -- an explicit instruction, not
        # the absence of one.
        orphans = set(self._live) - set(merged)
        # carry each orphan forward at the setting it is already running
        for symbol in orphans:
            merged[symbol] = self._live[symbol]
        # diff against what is live right now. Orphans never appear here,
        # because by construction their setting did not change.
        changes = {s: (self._live.get(s, "-"), label)
                   for s, label in merged.items() if self._live.get(s) != label}
        # swap atomically for the quoting thread: rebinding the whole dict, not
        # mutating it in place, so a reader sees the old config or the new one
        # and never a half-applied mixture of the two
        with self._lock:
            self._live = merged
            self._overridden = overridden
            self._orphans = orphans
            self._hashes = hashes
            self.last_good_ts = time.time()
        # what moved
        return changes

    def refresh(self) -> Dict[str, Tuple[str, str]]:
        """Call every REFRESH_SECONDS. NEVER RAISES. Returns changes applied."""
        try:
            # try to pick up the new files
            changes = self._load()
        except Exception as exc:                        # noqa: BLE001
            # RELOAD POLICY: keep the last good config, shout, carry on
            self.consecutive_failures += 1
            log.error("psx_config reload REJECTED (%d in a row), keeping the "
                      "config loaded at %s: %s", self.consecutive_failures,
                      time.strftime("%H:%M:%S",
                                    time.localtime(self.last_good_ts or 0)),
                      exc)
            # nothing changed
            return {}
        # a clean load resets the alert counter
        self.consecutive_failures = 0
        # AUDIT TRAIL: every change, named, so post-trade can explain the day
        for symbol, (old, new) in sorted(changes.items()):
            log.warning("psx_config CHANGE %-8s %-9s -> %-9s%s", symbol, old,
                        new, "  (override)" if symbol in self._overridden
                        else "")
        # ORPHAN WARNING, re-emitted EVERY reload rather than once. A name that
        # has fallen out of the assignment keeps trading on its old setting, by
        # design -- but that is exactly the state nobody notices, so it is said
        # again every three minutes until the file is fixed or DROP is written.
        with self._lock:
            orphans = sorted(self._orphans)
        # only when there are some
        if orphans:
            log.warning("psx_config ORPHANS still quoting on their last "
                        "setting, absent from %s: %s  -- write DROP against "
                        "them to stop them, or re-add them to the assignment",
                        self.assignment_path.name, ", ".join(orphans))
        # what moved
        return changes

    # ---- what the quoter asks --------------------------------------------
    def params_for(self, symbol: str) -> Optional[dict]:
        """Engine kwargs for one symbol, or None if it is not in the book.

        Returns e.g. {"queue_skew_ticks": 2.0, "queue_skew_thresh": 0.15,
                      "quote": True, "label": "QT_2t@15",
                      "drop_semantics": None}
        """
        # read under the lock so a reload cannot swap the dict mid-lookup
        with self._lock:
            label = self._live.get(symbol.strip().upper())
        # a symbol the refit never assigned is not tradeable -- say so
        # explicitly rather than returning a default the caller might quote on
        if label is None:
            return None
        # the numbers this label stands for
        ticks, thresh, quote = ENGINE_PARAMS[label]
        # what the strategy gets built with
        out = {
            # the lean, in ticks; 0.0 means the lean is off
            "queue_skew_ticks": ticks,
            # how lopsided the book must be before the lean fires
            "queue_skew_thresh": thresh,
            # False means this name is pulled -- see drop_semantics
            "quote": quote,
            # the machine label, for logging and P&L attribution
            "label": label,
            # only meaningful when quote is False; the caller acts on it
            "drop_semantics": None if quote else DROP_SEMANTICS,
        }
        # DROP under "no_add" needs NO engine change -- micro_mm's soft_inv
        # band already is this mechanism: once |pos| > soft_inv, the side that
        # would ADD to the position stops being quoted, so fills can only
        # reduce. soft_inv=0 therefore means "never add, only work out".
        if not quote and DROP_SEMANTICS == "no_add":
            # once holding anything at all, quote the reducing side only
            out["soft_inv"] = 0
            # CAVEAT the caller must honour: soft_inv=0 does NOT stop a FLAT
            # name from quoting both sides, because the band only binds at
            # |pos| > 0. So a dropped name that is already flat must be skipped
            # entirely -- do not construct a strategy for it:
            #   position == 0  -> do not quote this symbol at all
            #   position != 0  -> quote with these kwargs, which works the
            #                     inventory off passively and never adds to it
            out["skip_if_flat"] = True
        # the kwargs
        return out

    def strategy_kwargs(self, symbol: str) -> Optional[dict]:
        """Just the arguments micro_mm's constructor takes.

        params_for() carries control-plane fields -- quote, label,
        drop_semantics, skip_if_flat -- that the strategy has no parameter for.
        Passing the whole dict through would raise TypeError on the first
        symbol, so the split is here rather than at every call site.
        """
        # the full picture
        params = self.params_for(symbol)
        # never assigned
        if params is None:
            return None
        # the constructor arguments, and nothing else
        return {k: v for k, v in params.items()
                if k in ("queue_skew_ticks", "queue_skew_thresh", "soft_inv")}

    def symbols(self, quoting_only: bool = True) -> list:
        """The symbols in the book. quoting_only=True excludes the DROP names."""
        # a snapshot, taken under the lock
        with self._lock:
            items = list(self._live.items())
        # sorted, so logs and diffs are stable between runs
        return sorted(s for s, label in items
                      if (ENGINE_PARAMS[label][2] or not quoting_only))

    def orphans(self) -> list:
        """Symbols still quoting but no longer in the assignment file."""
        # a snapshot
        with self._lock:
            return sorted(self._orphans)

    def counts(self) -> Dict[str, int]:
        """How many names are on each setting."""
        # a snapshot
        with self._lock:
            live = list(self._live.values())
        # every known label, including the ones nobody is on
        return {label: sum(1 for v in live if v == label)
                for label in ENGINE_PARAMS}

    def summary(self) -> str:
        """One line for the startup log and for any health endpoint."""
        # a snapshot
        with self._lock:
            total = len(self._live)
            overridden = len(self._overridden)
            orphans = len(self._orphans)
        # the per-setting tally
        counts = self.counts()
        # the line
        return (f"{total} names | "
                + " ".join(f"{label}={counts[label]}"
                           for label in ENGINE_PARAMS)
                + f" | {overridden} override(s)"
                # only mention orphans when there are some, so the normal line
                # stays clean and the abnormal one stands out
                + (f" | {orphans} ORPHAN(S)" if orphans else "")
                + " | loaded "
                + time.strftime("%H:%M:%S",
                                time.localtime(self.last_good_ts or 0)))


def preflight(assignment_path, overrides_path=None) -> int:
    """Validate the current files before a session opens. 0 = safe to start."""
    # print at INFO so the preflight is readable in a terminal
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        # this raises if either file is unusable
        cfg = LiveConfig(assignment_path, overrides_path)
    except Exception as exc:                            # noqa: BLE001
        # name the problem and refuse
        print(f"PREFLIGHT FAILED -- do not start the book\n  {exc}")
        return 1
    # the headline
    print(f"PREFLIGHT OK\n  {cfg.summary()}")
    print(f"  assignment: {cfg.assignment_path}")
    # the overrides file legitimately may not be there
    exists = cfg.overrides_path is not None and cfg.overrides_path.exists()
    print(f"  overrides : {cfg.overrides_path}"
          f"{'' if exists else '  (absent -- normal)'}")
    print(f"  drop semantics: {DROP_SEMANTICS}")
    # the pulled names are the ones worth eyeballing
    pulled = [s for s in cfg.symbols(quoting_only=False)
              if s not in cfg.symbols()]
    print(f"  not quoted ({len(pulled)}): {', '.join(pulled) or '-'}")
    # at startup there can be no orphans by definition, but print the line at a
    # fixed place so a preflight after a mid-session restart shows them
    orphans = cfg.orphans()
    print(f"  orphans ({len(orphans)}): {', '.join(orphans) or '- none'}")
    # safe to start
    return 0


if __name__ == "__main__":
    # argv, so the paths stay injected even here
    import sys
    # the assignment is required; the overrides file is optional
    if len(sys.argv) < 2:
        raise SystemExit(
            "usage: python -m venues.psx_config "
            "<config_assignment_*.csv> [live_overrides.csv]")
    # run it and use the exit code
    raise SystemExit(preflight(sys.argv[1],
                               sys.argv[2] if len(sys.argv) > 2 else None))
